package com.tc.app.exchangemonitor.controller;

import java.io.Serializable;


/**
 * FutureTradeItem generated by hbm2java
 */
public class FutureTradeItem extends TradeItem implements Serializable
{
}