package gr.persons.entities;
// Generated Jul 15, 2011 10:15:10 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="PERSON")
public class Person  implements java.io.Serializable {


     private BigDecimal id;
     private String name;
     private String surname;
     private Date birthdate;
     private String sex;

    public Person() {
    }

	
    public Person(BigDecimal id) {
        this.id = id;
    }
    public Person(BigDecimal id, String name, String surname, Date birthdate, String sex) {
       this.id = id;
       this.name = name;
       this.surname = surname;
       this.birthdate = birthdate;
       this.sex = sex;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="SURNAME", length=50)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="BIRTHDATE", length=7)
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    
    @Column(name="SEX", length=8)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }




}


